/**
 * app_settings.ts
 * aws-serverless
 * Created by KhiemP <khiemp@vitalify.asia> on 08/11/25
 * Copyright (c) 2025 VFA Asia Co.,Ltd. All rights reserved.
 */
export const APP_SETTINGS = {
  API_KEY: Buffer.from('OMRON BP DIARY 20180226').toString('base64'),
  mail_from: {
    JP: 'ohqit_support@ohq.omron.co.jp',
    IN: 'ohsid_feedback@ap.omron.com',
    AU: 'sales@omronhealthcare.com.au',
    SG: 'ohs_feedback@ap.omron.com',
    TH: 'ohsth_csupport@ap.omron.com',
    PH: 'ohsph_feedback@ap.omron.com',
    VN: 'omronhealthcarevn@ap.omron.com',
    MY: 'ohsmy_feedback@ap.omron.com',
    INDO: 'callcentre@ap.omron.com',
  },
  mail_reply: 'ogsc_support@ssa.omron.co.jp',
  mail_from2: 'noreply@bp-manager.com',
  mail_bcc: '',
  mail_username: '',
  mail_password: '',
  mail_host: '',
  mail_subject: 'OMRON Graph Report',
  mail_pre_file: {
    EN: '[BP-Logbook]',
    JA: '[血圧手帳]',
    ZH: '[血壓手帳]',
    'ZH-HANS': '[血压手帐]',
    KO: '[혈압수첩]',
    DE: '[BD-Logbuch]',
    FR: '[Carnet de bord de TA]',
    IT: '[Registro PA]',
    ES: '[Registro TA]',
    NL: '[BD-Logboek]',
    PL: '[BP-Logbook]',
    SV: '[BP-Logbook]',
    TR: '[BP-Logbook]',
    PT: '[Livro de registros]',
    VI: '[Nhật ký huyết áp]',
  },
  mail_to_name: 'OGSCクラウドのお客様',
  ga_code: 'UA-69193763-18',
  redirect_uri: 'https://52.199.120.104/ogsc',
  USER_INFO_URL: '/oauth2/users/me/openid-connect',
  MEASURE_DATE_URL: '/server-code/versions/current/measureData',
  MEASURE_LATEST: '/server-code/versions/current/getLatestMeasureData',
  TOKEN_URL: '/oauth2/token',
  LOGIN_URL: '/oauth2/login',
  DEVICE_URL: '/server-code/versions/current/searchDeviceConfData',
  WITHDRAWAL_URL: '/system/withdrawn-user-information',
  SUPPORT_LANG: ['ZH', 'JA'],
  DEFAULT_LANG: 'JA',
  DEFAULT_SYS: 135,
  DEFAULT_DIA: 85,
  EMOJI_REGEX:
    '([*#0-9](?:\\xEF\\xB8\\x8F)?\\xE2\\x83\\xA3|\\xC2[\\xA9\\xAE]|\\xE2..(?:\\xF0\\x9F\\x8F[\\xBB-\\xBF])?(?:\\xEF\\xB8\\x8F)?|\\xE3(?:\\x80[\\xB0\\xBD]|\\x8A[\\x97\\x99])(?:\\xEF\\xB8\\x8F)?|\\xF0\\x9F(?:[\\x80-\\x86].(?:\\xEF\\xB8\\x8F)?|\\x87.\\xF0\\x9F\\x87.|..(?:\\xF0\\x9F\\x8F[\\xBB-\\xBF])?|(((?:\\xE2\\x80\\x8D)\\xE2\\x9D\\xA4\\xEF\\xB8\\x8F(?:\\xF0\\x9F..)?|(?:\\xE2\\x80\\x8D\\xF0\\x9F\\x91.){2,3}))?))',
  BP_COUNT: 2,
  PDF_TITLE_JA: '[OMRON connect]血圧手帳送付のご案内',
  PDF_TITLE_EN: '[OMRON connect]Sending Your BP-Logbook',
  PDF_TITLE_ZH: '[OMRON connect]如何寄送您的血壓手帳',
  PDF_TITLE_SUB: {
    JA: '血圧手帳（ 朝晩平均 ）',
    EN: 'Blood Pressure Logbook ( Morning & Evening BP Avg. )',
    ZH: '血壓手帳（早晚平均）',
  },
  PDF_DATE_OUTPUT: 'YYYY/MM/DD HH:mm',
  PDF_DATE_FORMAT: {
    JA: 'Y年M月D日',
    EN: 'M/D/Y',
    ZH: 'Y年m月d日',
  },
  PDF_MONTH_FORMAT: 'M/D',
  PDF_ONLY_MONTH: 'M',
  PDF_LOCALE: {
    JA: 'ja_JP',
    EN: 'en_EN',
    ZH: 'zh_CN',
  },
  PDF_ONLY_DAY: 'D',
  PDF_ONLY_DAY_OF_WEEK: 'D',
  PDF_WEEK_FORMAT: 'M/D',
  PDF_DAY_FORMAT: {
    JA: 'Y年M月D日',
    EN: 'Y M D',
    ZH: 'Y年m月d日',
  },
  PDF_DATE_SEPARATE: '〜',
  PDF_NAME: {
    JA: '名前：',
    EN: 'Name: ',
    ZH: '姓名：',
  },
  PDF_DATE_CREATE: {
    JA: '出力日時: ',
    EN: 'Created: ',
    ZH: '輸出日期: ',
  },
  PDF_FOOTER_LINE1: {
    JA: '医師の方へ',
    EN: 'For Healthcare Professional',
    ZH: '給醫師',
  },
  PDF_FOOTER_LINE2: {
    JA: '※本グラフでは高血圧治療ガイドラインに準じ、起床時および就寝前の血圧値のみを表記しています。',
    EN: '*This graph reflects only morning and evening blood pressure measurements as per hypertension treatment guidelines.',
    ZH: '※本圖表根據高血壓治療指南，只會顯示起床跟睡前的血壓值。',
  },
  PDF_WEEK_HINT_MODE_NIGHT: {
    JA: 'モード',
    EN: 'Mode',
    ZH: '模式',
  },
  PDF_WEEK_HINT_MODE_NIGHT_DES: {
    JA: '夜間モードで測定時に表示',
    EN: 'Displayed when measured in night mode',
    ZH: '在 夜眠期模式中測量時就會顯示',
  },
  PDF_WEEK_HINT_MODE_DAY: {
    JA: 'モード',
    EN: 'Mode',
  },
  PDF_WEEK_HINT_MODE_DAY_DES: {
    JA: '昼間モードで測定時に表示',
    EN: 'Displayed when measured in day mode',
  },
  PDF_WEEK_HINT_MEASURE: {
    JA: '測定',
    EN: 'Measure',
  },
  PT: {
    title: '[OMRON connect]Enviando seu livro de registros de pressão arterial',
    body: `Prezado tpl_user,<br/><br/>
        Agradecemos por utilizar nossos serviços de tratamento da pressão arterial e o OMRON connect.<br/>
        Estamos enviando em anexo o livro de registros de pressão arterial exportado.<br/>
        <br/>
        tpl_filename<br/>
        <br/>
        Atenciosamente,<br/>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br/>
        OMRON connect<br/>
        https://www.omronconnect.com/<br/>
        <br/>
        Copyright (c) 2016 OMRON HEALTHCARE Co., Ltd.  Todos os direitos reservados.<br/>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br/>
        *Este e-mail foi enviado de um endereço apenas para notificações e que não recebe e-mails. Não responda a esta mensagem.<br/>
        *Caso não tenha utilizado nosso serviço ou o nome de usuário não seja o seu, por gentileza, encaminhe este e-mail para "tpl_mail".`,

    // Constants for PDF template send mail
    PDF_TITLE: 'Registro da Pressão Arterial (média da PA matinal e noturna)',
    PDF_TITLE_SUB: 'Média/semanal.',
    PDF_DATE_OUTPUT: 'YYYY/MM/DD HH:mm',
    PDF_DATE_FORMAT: 'D/M/Y',
    PDF_MONTH_FORMAT: 'M/D',
    PDF_ONLY_MONTH: 'M',
    PDF_LOCALE: 'en_EN',
    PDF_ONLY_DAY: 'D',
    PDF_ONLY_DAY_OF_WEEK: 'D',
    PDF_WEEK_FORMAT: 'M/D',
    PDF_DAY_FORMAT: 'D/M/Y',
    PDF_DATE_SEPARATE: ' ~ ',
    PDF_NAME: 'Nome: ',
    PDF_DATE: 'Data',
    PDF_DATES: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
    PDF_MONTH: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
    PDF_BP: 'Pressão arterial',
    PDF_TIME: 'Hora',
    PDF_SYS: 'SYS',
    PDF_DIA: 'DIA',
    PDF_PULSE: 'Pulse',
    PDF_CONSULTATION: 'Consulta',
    PDF_MEDICATION: 'Medicamento',
    PDF_NOTES: 'Anotações',
    PDF_NOTES2: 'Anotações',
    PDF_PERIOD: 'Periodo',
    PDF_AVG: 'Dias medidos/semana.',
    PDF_AVG_PERIOD: 'Média/período',
    PDF_AVG_TEXT: 'Méd.',
    PDF_DATE_CREATE: 'Criar PDF em: ',
    PDF_FOOTER_LINE1: 'Aos profissionais de saúde',
    PDF_FOOTER_LINE2:
      '* This chart is plotted only with blood pressure values around waking time and bedtime according to hypertensive treatment guidelines.',
    PDF_FOOTER_LINE2_SUB: '&nbsp;&nbsp;&nbsp;Please use the data as a reference in your treatment plan.',
    PDF_FOOTER_LINE3: 'Pressão arterial matinal e pulso',
    PDF_FOOTER_LINE4: 'Pressão arterial noturna e pulso',
    PDF_FOOTER_LINE3_2:
      'Média das 2 primeiras leituras realizadas dentro de 10 minutos entre mor_start e mor_end da manhã.',
    PDF_FOOTER_LINE4_2: 'Média das 2 últimas leituras realizadas dentro de 10 minutos entre eve_start e eve_end.',
    PDF_NEXT_DAY: '',
    PDF_FOOTER_LINE5:
      'Se o número de medições for menor do que três, a média será calculada com base no número de medições realizadas.',
    PDF_TITLE_CSV: 'Data da medição,Fuso horário,SYS,DIA,Pulse,Nome do modelo do dispositivo',
    PDF_LESSTHAN_TEXT: 'Abaixo de',
    PDF_YOUR_TARGET_SYS: 'Sua meta de pressão SYS',
    PDF_YOUR_TARGET_DIA: 'Sua meta de pressão DIA',
    PDF_ACHIEVEMENT_LEVEL: 'Nível de desempenho',
    PDF_TARGET_ACHIEVED: 'Meta alcançada',
    PDF_EQUAL_OR_SLIGHTLY_1: 'Igual ou',
    PDF_EQUAL_OR_SLIGHTLY_2: 'ligeiramente',
    PDF_EQUAL_OR_SLIGHTLY_3: 'acima',
    PDF_HIGHER: 'Acima',
    PDF_MUCH_HIGHER: 'Muito acima',
    PDF_DAY_AVG_TITLE: 'Livro de registro da pressão arterial ( Média diária )',
    PDF_DAY_AVG_FOOTER_1: 'Média diária',
    PDF_DAY_AVG_FOOTER_2: 'Média de todas as medições em um dia.',
    PDF_WEEK_AVG_TITLE: 'Livro de registro da pressão arterial ( Lista )',
    PDF_WEEK_AVG_NAME: 'Nome',
    PDF_WEEK_AVG_HEADER: 'Média semanal',
    PDF_WEEK_PERIOD: 'Periodo',
    PDF_WEEK_MOR_AVG: 'Média manhã',
    PDF_WEEK_EVE_AVG: 'Média noite',
    PDF_WEEK_DAY_AVG: 'Média diária',
    PDF_WEEK_SYS: 'SYS',
    PDF_WEEK_DIA: 'DIA',
    PDF_WEEK_PULSE: 'Pulse',
    PDF_WEEK_ALL_RECORD_HEADER: 'Todas as leituras',
    PDF_WEEK_HINT_MODE_HEADER: 'Modo, Informações detectadas (I.D.)',
    PDF_WEEK_HINT_HEADER: 'Informações detectadas (I.D.)',
    PDF_WEEK_HIND_NOTES: 'Ícone de anotações',
    PDF_WEEK_HINT_MODE: 'Mode',
    PDF_WEEK_HINT_MODE_DES: 'É exibido ao medir no modo de Afib.',
    PDF_WEEK_HINT_MODE_NIGHT: 'Mode',
    PDF_WEEK_HINT_MODE_NIGHT_DES: 'É exibido ao medir no modo noturno.',
    PDF_WEEK_HINT_MEASUREMENT_ERROR: 'Erro de medição',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC: 'Não foi possível realizar a medição corretamente.',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT: 'Batimentos irregularesa',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC_1: 'Foi detectado ritmo cardíaco irregular duas ou mais vezes ',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC_2: 'durante uma medição.',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_B_1: 'É exibido ao detectar um erro no indicador de posicionamento,',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_B_2: 'na guia da braçadeira ou no movimento corporal',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_B_3: 'durante a medição.',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC_B_1: 'Foi detectado ritmo cardíaco irregular duas ou mais vezes',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC_B_2: 'durante uma medição.',
    PDF_WEEK_HINT_AFIB: 'Afib',
    PDF_WEEK_HINT_AFIB_DESC_1: 'Exibe quando uma possível fibrilação atrial (AFib) é detectada',
    PDF_WEEK_HINT_AFIB_DESC_2: 'durante a medição.',
    PDF_WEEK_HINT_EXCERCISE: 'Exercício',
    PDF_WEEK_HINT_LACK_OF_EXCERCISE: 'Falta de exercício',
    PDF_WEEK_HINT_REDUCING_SALT: 'Redução de sal',
    PDF_WEEK_HINT_SALT: 'Sal',
    PDF_WEEK_HINT_VEGETABLES: 'Vegetais',
    PDF_WEEK_HINT_LESS_VEGETABLES: 'Poucos vegetais',
    PDF_WEEK_HINT_NO_ALCOHOL: 'Sem álcool',
    PDF_WEEK_HINT_ALCOHOL: 'Álcool',
    PDF_WEEK_HINT_SLEEP: 'Sono',
    PDF_WEEK_HINT_LACK_OF_SLEEP: 'Falta de sono',
    PDF_WEEK_HINT_NOT_SMOKING: 'Sem fumar',
    PDF_WEEK_HINT_SMOKING: 'Fumar',
    PDF_WEEK_HINT_CONSULTATION: 'Hospital',
    PDF_WEEK_HINT_DETECT_INFOMATION: 'Informações detectadas (I.D.)',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_1: 'É exibido ao detectar um erro no indicador de ',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_2: 'posicionamento, na guia da braçadeira ou no ',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_3: 'movimento corporal durante a medição.',
    PDF_WEEK_DATE: 'Data',
    PDF_WEEK_TIME: 'Hora',
    PDF_WEEK_DI: 'I.D.',
    PDF_WEEK_MED: 'Med.',
    PDF_WEEK_NOTES: 'Anotações',
    PDF_PAGE: 'página ',
  },
  EN: {
    title: '[OMRON connect]Sending Your BP-Logbook',
    body: `Dear tpl_user,<br/><br/>
        Thank you for using our OMRON connect and Blood Pressure Management services.<br/>
        Please find the exported Blood Pressure Logbook attached to this email.<br/>
        <br/>
        tpl_filename<br/>
        <br/>
        Best regards,<br/>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br/>
        OMRON connect<br/>
        https://www.omronconnect.com/<br/>
        <br/>
        Copyright (c) 2016 OMRON HEALTHCARE Co., Ltd. All Rights Reserved.<br/>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br/>
        *This email message was sent from a notification-only address that cannot accept incoming email. Do not reply to this message.`,

    // Constants for PDF template send mail
    PDF_TITLE: 'Blood Pressure Logbook ( Morning & Evening BP Avg. )',
    PDF_TITLE_SUB: ' Average/wk.',
    PDF_DATE_OUTPUT: 'MMM D, YYYY HH:mm',
    PDF_DATE_FORMAT: 'D/M/Y',
    PDF_MONTH_FORMAT: 'MMM D',
    PDF_ONLY_MONTH: 'M',
    PDF_LOCALE: 'en_EN',
    PDF_ONLY_DAY: 'D',
    PDF_ONLY_DAY_OF_WEEK: 'D',
    PDF_WEEK_FORMAT: 'M D',
    PDF_DAY_FORMAT: 'M d D',
    PDF_DATE_SEPARATE: ' - ',
    PDF_NAME: 'Name: ',
    PDF_DATE: 'Date',
    PDF_DATES: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    PDF_MONTH: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    PDF_BP: 'BP',
    PDF_TIME: 'Time',
    PDF_SYS: 'SYS',
    PDF_DIA: 'DIA',
    PDF_PULSE: 'Pulse',
    PDF_CONSULTATION: 'Consultation',
    PDF_MEDICATION: 'Medication',
    PDF_NOTES: 'Notes',
    PDF_NOTES2: 'Notes',
    PDF_PERIOD: 'Period',
    PDF_AVG: 'Days measured/wk.',
    PDF_AVG_PERIOD: 'Average/period',
    PDF_AVG_TEXT: 'Avg',
    PDF_DATE_CREATE: 'Create PDF on: ',
    PDF_FOOTER_LINE1: 'To medical professionals',
    PDF_FOOTER_LINE2:
      '* This chart is plotted only with blood pressure values around waking time and bedtime according to hypertensive treatment guidelines.',
    PDF_FOOTER_LINE3: 'Morning Blood Pressure & Pulse',
    PDF_FOOTER_LINE4: 'Evening Blood Pressure & Pulse',
    PDF_FOOTER_LINE3_2: 'The average of the first 2 readings taken within 10 minutes between mor_start and mor_end.',
    PDF_FOOTER_LINE4_2: 'The average of the last 2 readings taken within 10 minutes between eve_start and eve_end.',
    PDF_NEXT_DAY: '',
    PDF_FOOTER_LINE5:
      'If the number of measurements is less than three, the average will be calculated based on the number of times measured.',
    PDF_TITLE_CSV: 'Measurement Date,Time Zone,SYS,DIA,Pulse,Device Model Name',
    PDF_LESSTHAN_TEXT: 'Less than',
    PDF_YOUR_TARGET_SYS: 'Your target SYS',
    PDF_YOUR_TARGET_DIA: 'Your target DIA',
    PDF_ACHIEVEMENT_LEVEL: 'Achievement Level',
    PDF_TARGET_ACHIEVED: 'Target Achieved',
    PDF_EQUAL_OR_SLIGHTLY_1: 'Equal or Slightly',
    PDF_EQUAL_OR_SLIGHTLY_2: 'Higher',
    PDF_HIGHER: 'Higher',
    PDF_MUCH_HIGHER: 'Much Higher',
    PDF_DAY_AVG_TITLE: 'Blood Pressure Logbook (Daily Avg.)',
    PDF_DAY_AVG_FOOTER_1: 'Daily Average',
    PDF_DAY_AVG_FOOTER_2: 'The average of all data measurement in a day.',
    PDF_WEEK_AVG_TITLE: 'Blood Pressure Logbook (List)',
    PDF_WEEK_AVG_NAME: 'Name',
    PDF_WEEK_AVG_HEADER: 'Weekly Average',
    PDF_WEEK_PERIOD: 'Period',
    PDF_WEEK_MOR_AVG: 'Morning Avg.',
    PDF_WEEK_EVE_AVG: 'Evening Avg.',
    PDF_WEEK_DAY_AVG: 'Daily Avg.',
    PDF_WEEK_SYS: 'SYS',
    PDF_WEEK_DIA: 'DIA',
    PDF_WEEK_PULSE: 'Pulse',
    PDF_WEEK_ALL_RECORD_HEADER: 'All Readings',
    PDF_WEEK_HINT_MODE_HEADER: 'Mode, Detected Info (D.I.)',
    PDF_WEEK_HINT_HEADER: 'Detected Info (D.I.)',
    PDF_WEEK_HIND_NOTES: 'Memo Icon',
    PDF_WEEK_HINT_MODE: 'Mode',
    PDF_WEEK_HINT_MODE_DES: 'Appears when measuring in Afib mode.',
    PDF_WEEK_HINT_MODE_NIGHT: 'Mode',
    PDF_WEEK_HINT_MODE_NIGHT_DES: 'Appears when measuring in nocturnal mode.',
    PDF_WEEK_HINT_MEASUREMENT_ERROR: 'Measurement Error',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_1: 'Appears when an error in Positioning Indicator,  Cuff Wrap Guide,',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_2: 'or Body Movement is detected during the measurement.',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT: 'Irregular heartbeat',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC_1: 'An irregular rhythm was detected two or more times during a',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC_2: 'measurement.',
    PDF_WEEK_HINT_AFIB: 'Afib',
    PDF_WEEK_HINT_AFIB_DESC_1: 'Appears when Possible AFib (Atrial Fibrillation) is detected during',
    PDF_WEEK_HINT_AFIB_DESC_2: 'measurement.',
    PDF_WEEK_HINT_EXCERCISE: 'Exercise',
    PDF_WEEK_HINT_LACK_OF_EXCERCISE: 'Lack of Exercise',
    PDF_WEEK_HINT_REDUCING_SALT: 'Reducing Salt',
    PDF_WEEK_HINT_SALT: 'Salt',
    PDF_WEEK_HINT_VEGETABLES: 'Vegetables',
    PDF_WEEK_HINT_LESS_VEGETABLES: 'Less vegetables',
    PDF_WEEK_HINT_NO_ALCOHOL: 'No alcohol',
    PDF_WEEK_HINT_ALCOHOL: 'Alcohol',
    PDF_WEEK_HINT_SLEEP: 'Sleep',
    PDF_WEEK_HINT_LACK_OF_SLEEP: 'Lack of sleep',
    PDF_WEEK_HINT_NOT_SMOKING: 'Not smoking',
    PDF_WEEK_HINT_SMOKING: 'Smoking',
    PDF_WEEK_HINT_CONSULTATION: 'Consultation',
    PDF_WEEK_HINT_DETECT_INFOMATION: 'Detected Info (D.I.)',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL: 'Pulse interval irregularity',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL_DESC_1: '"Pulse interval irregularity" is displayed when the pulse is',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL_DESC_2: 'always irregular during measurement.',
    PDF_WEEK_DATE: 'Date',
    PDF_WEEK_TIME: 'Time',
    PDF_WEEK_DI: 'D.I.',
    PDF_WEEK_MED: 'Med.',
    PDF_WEEK_NOTES: 'Notes',
    PDF_PAGE: 'Page ',
  },
  JA: {
    title: '[OMRON connect]血圧手帳送付のご案内',
    body: `tpl_user 様<br/><br/>
        日頃より弊社OMRON connect（オムロンコネクト）をご利用いただきありがとうございます。<br/>
        アプリから「らくらく血圧手帳」を作成された方にお送りしております。<br/>
        設定された期間で血圧手帳を作成いたしました。添付ファイルをご確認くださいませ。<br/>
        <br/>
        添付ファイル："tpl_filename"<br/>
        <br/>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br/>
        OMRON connect<br/>
        https://www.omronconnect.com/<br/>
        <br/>
        Copyright (c) 2016 OMRON HEALTHCARE Co., Ltd.  All Rights Reserved.<br/>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br/>
        ※本メールは送信専用アドレスから自動送信されています。返信を受信できないため、本メールに対するご返信はご遠慮下さい。`,
    PDF_TITLE: '血圧手帳（ 朝晩平均 ）',
    PDF_TITLE_SUB: ' 週平均',
    PDF_DATE_OUTPUT: 'YYYY/MM/DD HH:mm',
    PDF_DATE_FORMAT: 'YYYY年MM月DD日',
    PDF_MONTH_FORMAT: 'M/D',
    PDF_ONLY_MONTH: 'M',
    PDF_LOCALE: 'ja_JP',
    PDF_ONLY_DAY: 'D',
    PDF_ONLY_DAY_OF_WEEK: 'D',
    PDF_WEEK_FORMAT: 'M/D',
    PDF_DAY_FORMAT: 'YYYY年MM月DD日',
    PDF_DATE_SEPARATE: '〜',
    PDF_NAME: '名前：',
    PDF_DATE: '日 付',
    PDF_DATES: ['月', '火', '水', '木', '金', '土', '日'],
    PDF_MONTH: ['１月', '２月', '３月', '４月', '５月', '６月', '７月', '８月', '９月', '10月', '11月', '12月'],
    PDF_BP: '血　　圧',
    PDF_TIME: '測定時刻',
    PDF_SYS: '最高血圧',
    PDF_DIA: '最低血圧',
    PDF_PULSE: '脈　　拍',
    PDF_CONSULTATION: '診察',
    PDF_MEDICATION: '服薬回数',
    PDF_NOTES: 'メモ（症状など）',
    PDF_NOTES2: '自由記入',
    PDF_PERIOD: '期 間',
    PDF_AVG: '測定日数',
    PDF_AVG_PERIOD: '期間全平均',
    PDF_AVG_TEXT: '平均',
    PDF_DATE_CREATE: '出力日時: ',
    PDF_FOOTER_LINE1: '医師の方へ',
    PDF_FOOTER_LINE2: '※本グラフでは高血圧治療ガイドラインに準じ、起床時および就寝前の血圧値のみを表記しています。',
    PDF_FOOTER_LINE3: '起床時（朝）の血圧/脈拍',
    PDF_FOOTER_LINE4: '就寝時（夜）の血圧/脈拍',
    PDF_FOOTER_LINE3_2:
      'mor_startからmor_endの時間帯で、最も早い時刻の測定記録から10分以内に測定した値のうち、最初から2回までの平均値です。',
    PDF_FOOTER_LINE4_2:
      'eve_startからeve_endの時間帯で、最も遅い時刻の測定記録から10分以内に測定した値のうち、最後から2回までの平均値です。',
    PDF_NEXT_DAY: '翌日',
    PDF_FOOTER_LINE5:
      '起床時、就寝前ともに10分以内に2回もしくは1回しか測定しなかった場合は、2回の平均値または1回の測定値が表示されます。',
    PDF_TITLE_CSV: '測定日,タイムゾーン,最高血圧（mmHg）,最低血圧（mmHg）,脈拍（bpm）,機種',
    PDF_LESSTHAN_TEXT: '未満',
    PDF_YOUR_TARGET_SYS: '目標最高血圧',
    PDF_YOUR_TARGET_DIA: '目標最低血圧',
    PDF_ACHIEVEMENT_LEVEL: '達成度',
    PDF_TARGET_ACHIEVED: '目標血圧値を達成',
    PDF_EQUAL_OR_SLIGHTLY_1: '目標血圧値と同じ',
    PDF_EQUAL_OR_SLIGHTLY_2: 'またはやや高い',
    PDF_HIGHER: '目標血圧値より高い',
    PDF_MUCH_HIGHER: '目標血圧値より非常に高い',
    PDF_DAY_AVG_TITLE: '血圧手帳（ 日中平均 ）',
    PDF_DAY_AVG_FOOTER_1: '日中平均',
    PDF_DAY_AVG_FOOTER_2: '1日の全ての測定値の平均',
    PDF_WEEK_AVG_TITLE: '血圧手帳（ 一覧 ）',
    PDF_WEEK_AVG_NAME: '名前',
    PDF_WEEK_AVG_HEADER: '週平均',
    PDF_WEEK_PERIOD: '期間',
    PDF_WEEK_MOR_AVG: '朝平均',
    PDF_WEEK_EVE_AVG: '晩平均',
    PDF_WEEK_DAY_AVG: '日中平均',
    PDF_WEEK_SYS: '最高血圧',
    PDF_WEEK_DIA: '最低血圧',
    PDF_WEEK_PULSE: '脈拍',
    PDF_WEEK_ALL_RECORD_HEADER: '全測定値',
    PDF_WEEK_HINT_MODE_HEADER: '測定モード、測定状態',
    PDF_WEEK_HINT_HEADER: '測定状態',
    PDF_WEEK_HIND_NOTES: 'メモアイコン',
    PDF_WEEK_HINT_MODE: 'モード',
    PDF_WEEK_HINT_MODE_DES: 'Afibモードで測定時に表示',
    PDF_WEEK_HINT_MODE_NIGHT: 'モード',
    PDF_WEEK_HINT_MODE_NIGHT_DES: '夜間モードで測定時に表示',
    PDF_WEEK_HINT_MEASUREMENT_ERROR: '測定エラー',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC:
      '測定時に測定姿勢ガイド、カフぴったり巻、体動のエラーが検知された場合に表示。',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT: '不規則脈波',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC_1: '測定中の脈波の間隔が不規則な状態を2回以上検知',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC_2: 'すると表示。',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC_B: '測定中の脈波の間隔が不規則な状態を2回以上検知すると表示。',
    PDF_WEEK_HINT_AFIB: 'Afib',
    PDF_WEEK_HINT_AFIB_DESC_1: 'Afib モードで測定中にAfibを検出すると表示。',
    PDF_WEEK_HINT_AFIB_DESC_2: '',
    PDF_WEEK_HINT_EXCERCISE: '運動',
    PDF_WEEK_HINT_LACK_OF_EXCERCISE: '運動不足',
    PDF_WEEK_HINT_REDUCING_SALT: '塩分控え目',
    PDF_WEEK_HINT_SALT: '塩分',
    PDF_WEEK_HINT_VEGETABLES: '野菜多め',
    PDF_WEEK_HINT_LESS_VEGETABLES: '野菜不足',
    PDF_WEEK_HINT_NO_ALCOHOL: '節酒',
    PDF_WEEK_HINT_ALCOHOL: 'お酒',
    PDF_WEEK_HINT_SLEEP: 'しっかり睡眠',
    PDF_WEEK_HINT_LACK_OF_SLEEP: '睡眠不足',
    PDF_WEEK_HINT_NOT_SMOKING: '禁煙',
    PDF_WEEK_HINT_SMOKING: '喫煙',
    PDF_WEEK_HINT_CONSULTATION: '病院',
    PDF_WEEK_HINT_DETECT_INFOMATION: '測定状態',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_1: '測定時に測定姿勢ガイド、カフぴったり巻、体動の',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_2: 'エラーが検知された場合に表示。',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_B_1: '測定時に測定姿勢ガイド、カフぴったり巻、体動のエラーが検知',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_B_2: 'された場合に表示。',
    PDF_WEEK_DATE: '日付',
    PDF_WEEK_TIME: '測定時刻',
    PDF_WEEK_DI: '測定状態',
    PDF_WEEK_MED: '服薬',
    PDF_WEEK_NOTES: 'メモ（症状など）',
    PDF_PAGE: 'Page ',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL: '脈間隔の乱れあり',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL_DESC: '「脈間隔の乱れあり」は測定中の脈が常に不規則な時に表示。',
  },
  ZH: {
    title: '[OMRON connect]如何寄送您的血壓手帳',
    body: `親愛的 tpl_user<br/><br/>
        感謝您使用OMRON connect 以及血壓管理服務。<br/>
        信件內容為「血壓手帳」的資料. 檔案已根據您選擇的期間匯出完畢，請見信件裡的附檔。<br/>
        <br/>
        tpl_filename<br/>
        <br/>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br/>
        OMRON connect<br/>
        https://www.omronconnect.com/<br/>
        <br/>
        Copyright (c) 2016 OMRON HEALTHCARE Co., Ltd.  All Rights Reserved.<br/>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br/>
        *本信件為自動發送.請勿回信至本信件。`,
    PDF_TITLE: '血壓手帳（早晚平均）',
    PDF_TITLE_SUB: ' 週平均',
    PDF_DATE_OUTPUT: 'YYYY/MM/DD HH:mm',
    PDF_DATE_FORMAT: 'YYYY年MM月DD日',
    PDF_MONTH_FORMAT: 'M/D',
    PDF_ONLY_MONTH: 'M',
    PDF_LOCALE: 'zh_CN',
    PDF_ONLY_DAY: 'D',
    PDF_ONLY_DAY_OF_WEEK: 'D',
    PDF_WEEK_FORMAT: 'M/D',
    PDF_DAY_FORMAT: 'YYYY年MM月DD日',
    PDF_DATE_SEPARATE: '〜',
    PDF_NAME: '姓名：',
    PDF_DATE: '日期',
    PDF_DATES: ['一', '二', '三', '四', '五', '六', '日'],
    PDF_MONTH: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
    PDF_BP: '血　　壓',
    PDF_TIME: '測量時間',
    PDF_SYS: '收縮壓',
    PDF_DIA: '舒張壓',
    PDF_PULSE: '脈　　搏',
    PDF_CONSULTATION: '診斷',
    PDF_MEDICATION: '服藥次數',
    PDF_NOTES: '備註(症狀等)',
    PDF_NOTES2: '自由記錄',
    PDF_PERIOD: '期 間',
    PDF_AVG: '一週內測量天數',
    PDF_AVG_PERIOD: '期間內平均',
    PDF_AVG_TEXT: '平均',
    PDF_DATE_CREATE: '輸出日期: ',
    PDF_FOOTER_LINE1: '給醫師',
    PDF_FOOTER_LINE2: '※本圖表根據高血壓治療指南，只會顯示起床跟睡前的血壓值。',
    PDF_FOOTER_LINE3: '起床（早晨）的血壓/脈搏',
    PDF_FOOTER_LINE4: '睡前（夜晚）的血壓/脈搏',
    PDF_FOOTER_LINE3_2: 'mor_start到mor_end這段時間內，最早時間的10分鐘內2次測量的血壓/脈搏平均值。',
    PDF_FOOTER_LINE4_2: 'eve_start到eve_end這段時間內，最晚時間的10分鐘內2次測量的血壓/脈搏平均值。',
    PDF_NEXT_DAY: '',
    PDF_FOOTER_LINE5: '起床時、睡前10分鐘內若只有測量2次或1次時，只會顯示2次的平均值或測量1次的數值。',
    PDF_TITLE_CSV: '測量日期,時區,收縮壓(mmHg),舒張壓(mmHg),脈搏(bpm),機種',
    PDF_LESSTHAN_TEXT: '小於',
    PDF_YOUR_TARGET_SYS: '目標收縮壓',
    PDF_YOUR_TARGET_DIA: '目標舒張壓',
    PDF_ACHIEVEMENT_LEVEL: '成果等級',
    PDF_TARGET_ACHIEVED: '達到目標',
    PDF_EQUAL_OR_SLIGHTLY_1: '等於或略高',
    PDF_EQUAL_OR_SLIGHTLY_2: '',
    PDF_HIGHER: '較高',
    PDF_MUCH_HIGHER: '高出很多',
    PDF_DAY_AVG_TITLE: '血壓手帳（一日平均）',
    PDF_DAY_AVG_FOOTER_1: '一日平均',
    PDF_DAY_AVG_FOOTER_2: '一天中全部測量值的平均',
    PDF_WEEK_AVG_TITLE: '血壓記錄表',
    PDF_WEEK_AVG_NAME: '姓名: ',
    PDF_WEEK_AVG_HEADER: '一週平均',
    PDF_WEEK_PERIOD: '期間內平均',
    PDF_WEEK_MOR_AVG: '晨報平均',
    PDF_WEEK_EVE_AVG: '平均晚報',
    PDF_WEEK_DAY_AVG: '一日平均',
    PDF_WEEK_SYS: '收縮壓',
    PDF_WEEK_DIA: '舒張壓',
    PDF_WEEK_PULSE: '脈搏',
    PDF_WEEK_ALL_RECORD_HEADER: '全部測量值',
    PDF_WEEK_HINT_MODE_HEADER: '模式, 測量狀態',
    PDF_WEEK_HINT_HEADER: '測量狀態',
    PDF_WEEK_HIND_NOTES: '狀況備註',
    PDF_WEEK_HINT_MODE: '模式',
    PDF_WEEK_HINT_MODE_DES: '在 Afib 模式中測量時就會顯示',
    PDF_WEEK_HINT_MODE_NIGHT: '模式',
    PDF_WEEK_HINT_MODE_NIGHT_DES: '在 夜眠期模式中測量時就會顯示',
    PDF_WEEK_HINT_MEASUREMENT_ERROR: '測量錯誤',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_1: '測量過程中若偵測到「測量高度指引」、「壓脈帶著裝確認」或',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_2: '「身體晃動檢測」有誤，就會顯示。',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT: '不規則脈波',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC: '測量過程中偵測到二或多次不規則脈波時就會顯示。',
    PDF_WEEK_HINT_AFIB: 'Afib',
    PDF_WEEK_HINT_AFIB_DESC: '測量中檢測到可能的房顫 (AFib) 時顯示。',
    PDF_WEEK_HINT_EXCERCISE: '運動',
    PDF_WEEK_HINT_LACK_OF_EXCERCISE: '運動不足',
    PDF_WEEK_HINT_REDUCING_SALT: '少鹽日',
    PDF_WEEK_HINT_SALT: '攝取鹽分',
    PDF_WEEK_HINT_VEGETABLES: '多蔬菜',
    PDF_WEEK_HINT_LESS_VEGETABLES: '少蔬菜',
    PDF_WEEK_HINT_NO_ALCOHOL: '無喝酒',
    PDF_WEEK_HINT_ALCOHOL: '喝酒',
    PDF_WEEK_HINT_SLEEP: '睡眠充足',
    PDF_WEEK_HINT_LACK_OF_SLEEP: '睡眠不足',
    PDF_WEEK_HINT_NOT_SMOKING: '禁煙',
    PDF_WEEK_HINT_SMOKING: '抽煙',
    PDF_WEEK_HINT_CONSULTATION: '診斷',
    PDF_WEEK_HINT_DETECT_INFOMATION: '測量狀態',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL: 'Pulse interval irregularity',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL_DESC_1: '"Pulse interval irregularity" is displayed when the pulse is',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL_DESC_2: 'always irregular during measurement.',
    PDF_WEEK_DATE: '日期',
    PDF_WEEK_TIME: '測量時間',
    PDF_WEEK_DI: '測量狀態',
    PDF_WEEK_MED: '服藥',
    PDF_WEEK_NOTES: '備註(症狀等)',
    PDF_PAGE: '頁 ',
  },
  'ZH-HANS': {
    title: '[欧姆龙笔记]血压手账发送向导',
    body: `tpl_user 先生/女士,<br/><br/>
        感谢您一直以来使用本公司的OMRON connect。<br/>
        我们通过应用向创建了"血压手账"的用户发送手账信息。<br/>
        已根据您设置的期间创建了血压手账。请确认附件。<br/>
        <br/>
        tpl_filename<br/>
        <br/>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br/>
        OMRON connect<br/>
        https://www.omronconnect.com/<br/>
        <br/>
        Copyright (c) 2016 OMRON HEALTHCARE Co., Ltd. All Rights Reserved.<br/>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br/>
        ※本电子邮件通过发件专用地址自动发送。我们无法接收回信，因此请勿回复本电子邮件。<br/>
        ※如果您对本内容没有印象，请直接将本邮件的正文转发通知到"tpl_mail"。`,
    PDF_TITLE: '血压手帐 (早晚平均)',
    PDF_TITLE_SUB: ' 周平均',
    PDF_DATE_OUTPUT: 'Y/m/d H:i',
    PDF_DATE_FORMAT: 'Y年m月d日',
    PDF_MONTH_FORMAT: 'n/j',
    PDF_ONLY_MONTH: 'M',
    PDF_LOCALE: 'zh_ZH-CN',
    PDF_ONLY_DAY: 'j',
    PDF_ONLY_DAY_OF_WEEK: 'D',
    PDF_WEEK_FORMAT: 'n/j',
    PDF_DAY_FORMAT: 'Y年m月d日',
    PDF_DATE_SEPARATE: '〜',
    PDF_NAME: '姓名: ',
    PDF_DATE: '日期',
    PDF_DATES: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
    PDF_MONTH: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    PDF_BP: '血压',
    PDF_TIME: '测量时间',
    PDF_SYS: '高压',
    PDF_DIA: '低压',
    PDF_PULSE: '脉搏',
    PDF_CONSULTATION: '诊察',
    PDF_MEDICATION: '服药次数',
    PDF_NOTES: '备注（症状等）',
    PDF_NOTES2: '自由记录',
    PDF_PERIOD: '对象期间',
    PDF_AVG: '测量天数',
    PDF_AVG_PERIOD: '期间总平均',
    PDF_AVG_TEXT: '平均',
    PDF_DATE_CREATE: '输出日期及时间: ',
    PDF_FOOTER_LINE1: '致医生',
    PDF_FOOTER_LINE2: '※本图表根据高血压治疗指南，只显示起床时及睡前的血压值。',
    PDF_FOOTER_LINE3: '起床时（早晨）的血压/脉搏',
    PDF_FOOTER_LINE4: '睡前（夜间）的血压/脉搏',
    PDF_FOOTER_LINE3_2: 'mor_start～mor_end这段时间内，自最早时间的测量记录起10分钟内2次测量的平均值。',
    PDF_FOOTER_LINE4_2: 'eve_start～次日eve_end这段时间内，自最晚时间的测量记录起10分钟内2次测量的平均值。',
    PDF_NEXT_DAY: '',
    PDF_FOOTER_LINE5: '起床时、睡前的10分钟内均只测量了2次或1次时，则显示2次的平均值或1次的测量值。',
    PDF_TITLE_CSV: '测量日期,时区,高压（mmHg）,低压（mmHg）,脉搏（bpm）,机型',
    PDF_LESSTHAN_TEXT: '小于',
    PDF_YOUR_TARGET_SYS: '目标高压',
    PDF_YOUR_TARGET_DIA: '目标低压',
    PDF_ACHIEVEMENT_LEVEL: '达成度',
    PDF_TARGET_ACHIEVED: '达成目标',
    PDF_EQUAL_OR_SLIGHTLY_1: '等于或略高于',
    PDF_EQUAL_OR_SLIGHTLY_2: '目标血压值',
    PDF_HIGHER: '比目标血压值高',
    PDF_MUCH_HIGHER: '比目标血压值高很多',
    PDF_DAY_AVG_TITLE: '血压手帐（每日平均）',
    PDF_DAY_AVG_FOOTER_1: '每日平均',
    PDF_DAY_AVG_FOOTER_2: '一天中所有数据的平均值。',
    PDF_WEEK_AVG_TITLE: '血压记录表',
    PDF_WEEK_AVG_NAME: '姓名',
    PDF_WEEK_AVG_HEADER: '周平均',
    PDF_WEEK_PERIOD: '对象期间',
    PDF_WEEK_MOR_AVG: '晨报平均',
    PDF_WEEK_EVE_AVG: '平均晚报',
    PDF_WEEK_DAY_AVG: '每日平均',
    PDF_WEEK_SYS: '高压',
    PDF_WEEK_DIA: '低压',
    PDF_WEEK_PULSE: '脉搏',
    PDF_WEEK_ALL_RECORD_HEADER: '所有测量值',
    PDF_WEEK_HINT_MODE_HEADER: '模式, 测量状态',
    PDF_WEEK_HINT_HEADER: '测量状态',
    PDF_WEEK_HIND_NOTES: '状态标签图标',
    PDF_WEEK_HINT_MODE: '模式',
    PDF_WEEK_HINT_MODE_DES: '在Afib 模式测量时显示。',
    PDF_WEEK_HINT_MODE_NIGHT: '模式',
    PDF_WEEK_HINT_MODE_NIGHT_DES: '在夜晚模式中测量时显示',
    PDF_WEEK_HINT_MEASUREMENT_ERROR: '测量错误',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_1: '在测量过程中检测到手腕位置、袖带佩戴自检或误动作提示错误时',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_2: '显示。',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT: '不规则脉波',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC: '在测量过程中两次或多次检测到脉波间隔不规则时显示。',
    PDF_WEEK_HINT_AFIB: 'Afib',
    PDF_WEEK_HINT_AFIB_DESC: '测量中检测到可能的房颤 (AFib) 时显示。',
    PDF_WEEK_HINT_EXCERCISE: '运动',
    PDF_WEEK_HINT_LACK_OF_EXCERCISE: '运动不足',
    PDF_WEEK_HINT_REDUCING_SALT: '控盐',
    PDF_WEEK_HINT_SALT: '盐分',
    PDF_WEEK_HINT_VEGETABLES: '蔬菜丰富',
    PDF_WEEK_HINT_LESS_VEGETABLES: '蔬菜不足',
    PDF_WEEK_HINT_NO_ALCOHOL: '节酒',
    PDF_WEEK_HINT_ALCOHOL: '饮酒',
    PDF_WEEK_HINT_SLEEP: '睡眠充足',
    PDF_WEEK_HINT_LACK_OF_SLEEP: '睡眠不足',
    PDF_WEEK_HINT_NOT_SMOKING: '禁烟',
    PDF_WEEK_HINT_SMOKING: '吸烟',
    PDF_WEEK_HINT_CONSULTATION: '诊察',
    PDF_WEEK_HINT_DETECT_INFOMATION: '测量状态',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL: 'Pulse interval irregularity',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL_DESC_1: '"Pulse interval irregularity" is displayed when the pulse is',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL_DESC_2: 'always irregular during measurement.',
    PDF_WEEK_DATE: '日期',
    PDF_WEEK_TIME: '测量时间',
    PDF_WEEK_DI: '测量状态',
    PDF_WEEK_MED: '服药',
    PDF_WEEK_NOTES: '备注（症状等）',
    PDF_PAGE: '页 ',
  },
  ES: {
    title: '[OMRON connect]Envío del registro de tensión arterial',
    body: `Hola, tpl_user:<br/><br/>
        Gracias por utilizar OMRON connect y nuestros servicios de control de presión arterial.<br/>
        Encuentra el registro de presión arterial exportado como archivo adjunto en este correo electrónico.<br/>
        <br/>
        tpl_filename<br/>
        <br/>
        Saludos,<br/>
        <br/>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br/>
        OMRON connect<br/>
        https://www.omronconnect.com/<br/>
        <br/>
        Copyright (c) 2016 OMRON HEALTHCARE Co., Ltd. Todos los derechos reservados.<br/>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━<br/>
        *Este mensaje de correo electrónico se ha enviado desde una dirección solo para notificaciones y no puede aceptar un correo entrante. No responda a este mensaje.`,

    // Constants for PDF template send mail
    PDF_TITLE: 'Registro de presión arterial (Promedio Día y Noche)',
    PDF_TITLE_SUB: ' Media semanal',
    PDF_DATE_OUTPUT: 'd/m/Y H:i',
    PDF_DATE_FORMAT: 'd/m/Y',
    PDF_MONTH_FORMAT: 'j/n',
    PDF_ONLY_MONTH: 'M',
    PDF_LOCALE: 'es_ES',
    PDF_ONLY_DAY: 'j',
    PDF_ONLY_DAY_OF_WEEK: 'D',
    PDF_WEEK_FORMAT: 'j/n',
    PDF_DAY_FORMAT: 'd/m/Y',
    PDF_DATE_SEPARATE: '~',
    PDF_NAME: 'Nombre: ',
    PDF_DATE: 'Fecha',
    PDF_DATES: ['lun', 'mar', 'mié', 'jue', 'vie', 'sáb', 'dom'],
    PDF_MONTH: ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'],
    PDF_BP: 'Presión arterial',
    PDF_TIME: 'Hora',
    PDF_SYS: 'SYS',
    PDF_DIA: 'DIA',
    PDF_PULSE: 'Pulse',
    PDF_CONSULTATION: 'Consulta',
    PDF_MEDICATION: 'Medicamento',
    PDF_NOTES: 'Notas',
    PDF_NOTES2: 'Notas',
    PDF_PERIOD: 'Zeitraum',
    PDF_AVG: 'Días con mediciones/semana',
    PDF_AVG_PERIOD: 'Media/periodo',
    PDF_AVG_TEXT: 'Media',
    PDF_DATE_CREATE: 'Crear PDF: ',
    PDF_FOOTER_LINE1: 'Para profesionales de la salud',
    PDF_FOOTER_LINE2:
      '* Este gráfico se genera únicamente a partir de los valores de tensión arterial obtenidos a la hora de levantarse y de acostarse, tal y como establecen las directrices para el tratamiento de la hipertensión.',
    PDF_FOOTER_LINE3: 'Mañana presión arterial y pulso',
    PDF_FOOTER_LINE4: 'Noche presión arterial y pulso',
    PDF_FOOTER_LINE3_2:
      'La media de las primeras 2 lecturas obtenidas durante un periodo de 10 minutos entre las mor_start y las mor_end h.',
    PDF_FOOTER_LINE4_2:
      'La media de las últimas 2 lecturas obtenidas durante un periodo de 10 minutos entre las eve_start y las eve_end h.',
    PDF_NEXT_DAY: '',
    PDF_FOOTER_LINE5:
      'Si el número de mediciones es inferior a tres, la medida se calcula a partir del número de veces que se ha realizado la medición.',
    PDF_TITLE_CSV: 'Fecha de medición,Zona horaria,SYS,DIA,Pulso,Nombre del modelo de dispositivo',
    PDF_LESSTHAN_TEXT: 'Menos de',
    PDF_YOUR_TARGET_SYS: 'Su presión SYS objetivo',
    PDF_YOUR_TARGET_DIA: 'Su presión DIA objetivo',
    PDF_ACHIEVEMENT_LEVEL: 'Nivel de logro',
    PDF_TARGET_ACHIEVED: 'Objetivo conseguido',
    PDF_EQUAL_OR_SLIGHTLY_1: 'Igual o ligeramente',
    PDF_EQUAL_OR_SLIGHTLY_2: 'superior',
    PDF_HIGHER: 'Superior',
    PDF_MUCH_HIGHER: 'Muy superior',
    PDF_DAY_AVG_TITLE: 'Registro de presión arterial (Media diaria )',
    PDF_DAY_AVG_FOOTER_1: 'Media diaria',
    PDF_DAY_AVG_FOOTER_2: 'La media de todas las mediciones de datos obtenidas durante un día.',
    PDF_WEEK_AVG_TITLE: 'Registro de presión arterial ( Lista )',
    PDF_WEEK_AVG_NAME: 'Nombre',
    PDF_WEEK_AVG_HEADER: 'Promedio semanal',
    PDF_WEEK_PERIOD: 'Periodo',
    PDF_WEEK_MOR_AVG: 'Promedio de mañana',
    PDF_WEEK_EVE_AVG: 'Promedio de la tarde',
    PDF_WEEK_DAY_AVG: 'Media diaria',
    PDF_WEEK_SYS: 'SYS',
    PDF_WEEK_DIA: 'DIA',
    PDF_WEEK_PULSE: 'Pulse',
    PDF_WEEK_ALL_RECORD_HEADER: 'Todas las lecturas',
    PDF_WEEK_HINT_MODE_HEADER: 'Modo, Información detectada (I.D.)',
    PDF_WEEK_HINT_HEADER: 'Información detectada (I.D.)',
    PDF_WEEK_HIND_NOTES: 'Ícono de nota',
    PDF_WEEK_HINT_MODE: 'Modo',
    PDF_WEEK_HINT_MODE_DES: 'Aparece al medir en modo de Afib.',
    PDF_WEEK_HINT_MODE_NIGHT: 'Modo',
    PDF_WEEK_HINT_MODE_NIGHT_DES: 'Aparece al medir en modo nocturno.',
    PDF_WEEK_HINT_MEASUREMENT_ERROR: 'Error de medición',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_1: 'Aparece cuando se detecta un error en el indicador de posición,',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_2: 'en la guía de ajuste del brazalete o cuando se detecta',
    PDF_WEEK_HINT_MEASUREMENT_ERROR_DESC_3: 'movimiento corporal durante la medición.',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT: 'Latido arrítmico',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC_1: 'Se ha detectado un ritmo irregular en dos o más ocasiones',
    PDF_WEEK_HINT_IRREGULAR_HEARTBEAT_DESC_2: 'durante una medición.',
    PDF_WEEK_HINT_AFIB: 'Afib',
    PDF_WEEK_HINT_AFIB_DESC_1: 'Se muestra cuando se detecta una posible fibrilación auricular',
    PDF_WEEK_HINT_AFIB_DESC_2: '(AFib) durante la medición.',
    PDF_WEEK_HINT_EXCERCISE: 'Ejercicio',
    PDF_WEEK_HINT_LACK_OF_EXCERCISE: 'No ejercicio',
    PDF_WEEK_HINT_REDUCING_SALT: 'Sal reducida',
    PDF_WEEK_HINT_SALT: 'Sal',
    PDF_WEEK_HINT_VEGETABLES: 'Verdura',
    PDF_WEEK_HINT_LESS_VEGETABLES: 'Poca verdura',
    PDF_WEEK_HINT_NO_ALCOHOL: 'Sin alcohol',
    PDF_WEEK_HINT_ALCOHOL: 'Alcohol',
    PDF_WEEK_HINT_SLEEP: 'Sueño ',
    PDF_WEEK_HINT_LACK_OF_SLEEP: 'Falta de sueño',
    PDF_WEEK_HINT_NOT_SMOKING: 'Sin tabaco',
    PDF_WEEK_HINT_SMOKING: 'Con tabaco',
    PDF_WEEK_HINT_CONSULTATION: 'Hospital',
    PDF_WEEK_HINT_DETECT_INFOMATION: 'Información detectada (I.D.)',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL: 'Pulse interval irregularity',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL_DESC_1: '"Pulse interval irregularity" is displayed when the pulse is',
    PDF_WEEK_HINT_IRREGULAR_PULSE_INTERVAL_DESC_2: 'always irregular during measurement.',
    PDF_WEEK_DATE: 'Fecha',
    PDF_WEEK_TIME: 'Hora',
    PDF_WEEK_DI: 'I.D.',
    PDF_WEEK_MED: 'Med.',
    PDF_WEEK_NOTES: 'Notas',
    PDF_PAGE: 'Página ',
  },
};
