version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install
      - npm install --prefix ./src-layers
  pre_build:
    commands:
  build:
    commands:
      - npm run build
      # Create necessary directories
      - |
        mkdir -p dist/src-layers/nodejs
        mkdir dist/src/api-send_email_batch
        mkdir -p dist/src-layers/public
        mkdir -p dist/src-layers/resources
      
      # Create the S3 bucket if it does not exist
      - |
        BUCKET_NAME="lambda-rds-$REGION-$ENVIRONMENT-packaged-2086"
        if ! aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
          echo "Bucket does not exist. Creating bucket: $BUCKET_NAME"
          aws s3 mb s3://$BUCKET_NAME
        else
          echo "Bucket already exists: $BUCKET_NAME"
        fi
       
      # Use AWS SAM to package the application using AWS CloudFormation
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET_NAME --output-template-file packaged-template.yml

  post_build:
    commands:
      - echo "Build artifacts ready for deployment"

artifacts:
  files:
    - packaged-template.yml
  base-directory: '.'
