# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# License-Identifier: MIT
# Created by: KhiemPT <khiempt@vitalify.asia> on 2025/03/30

AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation template for Lambda, API Gateway, DynamoDB
Parameters:
  Stage:
    Type: String
    Description: Refers to the operational state of your resources
    Default: dev
    AllowedValues:
      - dev
      - stg
      - prod
      - test
  ProjectId:
    Type: String
    Description: ProjectId used to associate new resources to team members
    Default: lambda-rds
  PublicSubNetId1:
    Type: String
    Description: Public subnet 1
    Default: subnet-1
  PublicSubNetId2:
    Type: String
    Description: Public subnet 2
    Default: subnet-2
  SecurityGroupId:
    Type: String
    Description: Security group id
Conditions:
  IsProduction: !Equals [ !Ref Stage, prod ]
  IsProdOrStg: 
    Fn::Or:
      - Fn::Equals: [!Ref Stage, prod]
      - Fn::Equals: [!Ref Stage, stg]
      - Fn::Equals: [!Ref Stage, test]
  IsDevOrStg: 
    Fn::Or:
      - Fn::Equals: [!Ref Stage, dev]
      - Fn::Equals: [!Ref Stage, stg]
      - Fn::Equals: [!Ref Stage, test]
Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Runtime: nodejs22.x
    MemorySize: 512
    Timeout: 300
    Tracing: Active
    Layers:
      - !Ref SrcLayer
    Environment:
      Variables:
        STAGE: !Ref Stage
        REGION: !Ref AWS::Region
        MYSQL_HOST: !Sub '{{resolve:secretsmanager:${ProjectId}-${Stage}-secrets:SecretString:MYSQL_HOST}}'
        MYSQL_PORT: !Sub '{{resolve:secretsmanager:${ProjectId}-${Stage}-secrets:SecretString:MYSQL_PORT}}'
        MYSQL_DATABASE: !Sub '{{resolve:secretsmanager:${ProjectId}-${Stage}-secrets:SecretString:MYSQL_DATABASE}}'
        MYSQL_USER: !Sub '{{resolve:secretsmanager:${ProjectId}-${Stage}-secrets:SecretString:MYSQL_USER}}'
        MYSQL_PASSWORD: !Sub '{{resolve:secretsmanager:${ProjectId}-${Stage}-secrets:SecretString:MYSQL_PASSWORD}}'
    AutoPublishAlias: live
    Tags:
      Name: !Ref ProjectId
      Environment: !Ref Stage
      ProjectId: !Ref ProjectId
      
Resources:
  ApiGwAccountConfig:
    Type: "AWS::ApiGateway::Account"
    Properties:
      CloudWatchRoleArn: !GetAtt "ApiGatewayLoggingRole.Arn"

  ApiGatewayLoggingRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  SrcLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${ProjectId}-${Stage}-src-layers
      Description: Our managed service project leverages the Lambda layer to apply customized logic and analysis of high volume data
      ContentUri: dist/src-layers/
      CompatibleRuntimes:
        - nodejs22.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

  MyRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${ProjectId}-${Stage}"
      StageName: !Ref Stage
      Description:
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: '/*' # Allows for logging on any resource
          HttpMethod: '*' # Allows for logging on any method
      Cors:
        AllowMethods: "'POST,GET,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"
      
  Greetings:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectId}-${Stage}-api-get-greetings'
      CodeUri: ./dist/src/api-get-greetings
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api/get-greetings
            Method: get
            RestApiId: !Ref MyRestApi
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SecurityGroupId #get from vpc terraform
        SubnetIds:
          - !Ref PublicSubNetId1 #get from vpc terraform
          - !Ref PublicSubNetId2 #get from vpc terraform
  
  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "Lambda-${ProjectId}-${AWS::Region}-${Stage}-${AWS::AccountId}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [ lambda.amazonaws.com, backup.amazonaws.com]
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - !Sub "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        - !Sub "arn:aws:iam::aws:policy/AmazonSESFullAccess"
        - !Sub "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - !Sub "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
      Policies:
        - PolicyName: LambdaVpcAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - backup:*
                  - iam:PassRole
                  - kms:*
                  - elasticfilesystem:*
                  - batch:*
                Resource: "*"

Outputs:
  ApiEndpoint:
    Description: "API endpoint"
    Value: !Sub "https://${MyRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
  MyRestApiArn:
    Value: !Ref MyRestApi
    Export:
      Name: !Sub "${AWS::Region}-${Stage}-RestApiArn"
